CREATE DATABASE customer_behaviour;
USE customer_behaviour;
ALTER TABLE mytable RENAME TO customer;

#Q1) What is the total revenue generated by male vs female customer.
SELECT gender , SUM(purchase_amount) AS revenue FROM customer GROUP BY gender; 

#Q2) which customer used a discount but still spent more than the average purchase amount.
SELECT customer_id ,purchase_amount FROM customer WHERE discount_applied ="Yes" AND 
purchase_amount >=(SELECT AVG(purchase_amount) FROM customer);

#Q3) What are the top 5 products with highest review rating.
SELECT item_purchased,ROUND(AVG(review_rating),2) AS Average_review_rating 
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

#Q4) Compare the average purchase amounts between standard and express shipping.
SELECT shipping_type ,
ROUND(AVG(purchase_amount)) AS Avrage_purchase
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

#Q5)Do subscribed customers spend more?compare average spend and total revenue.
SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(AVG(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY avg_spend,total_revenue DESC;

#Q6)which 5 products have the highest percentage of purchases with discount applied
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied ='Yes' THEN 1 ELSE 0 END)/ COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

#Q7) segment customer into New,returning and loyal based on their total number of previous purchase
#     and show the count of each segment.
WITH customer_type AS (
SELECT customer_id,previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer
)

SELECT customer_segment,COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment

#Q8)What are the top 3 most purchased product within each category?
WITH item_counts AS (
SELECT category,
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)
SELECT item_rank , category, item_purchased,total_orders
FROM item_counts
WHERE item_rank <= 3;

#Q9)Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

#Q10) what are the revenue contribution of each age gruop
SELECT age_gruop,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_gruop
ORDER BY total_revenue DESC;





